### ISSUE TITLE
No reason to generate an auth token on this model

### ISSUE THREAD

**Issue by arthurbernierjr** [poyalex/unit-2-project#1]
https://github.com/poyalex/unit-2-project/blob/fa5bf3423d3d9c7e917e2c4ffb263c50a2e165b3/models/blog.js#L9-L13

Auth tokens are only for authentication, this only happens on users,  `blogs` don't log in and log out. Logging in and out is done by the user to create an auth token with their credentials. This token grants access to private information only for them, like `posts` and `comments`. After logout the token and the associated data is deleted from storage(this would be on the frontend).

**Comment by poyalex** [comment]
Had originally meant to comment this out instead of on the user.js models file. Originally had thought the blog model needed authentication, but realize that handled by the user model.
