### ISSUE TITLE
This is wrong, you should be creating a token here

### ISSUE THREAD

**Issue by arthurbernierjr** [poyalex/unit-2-project#2]
https://github.com/poyalex/unit-2-project/blob/fa5bf3423d3d9c7e917e2c4ffb263c50a2e165b3/models/user.js#L18-L21

You removed the auth generation here which is incorrect, the user should 100 percent be generating an auth token.

**Comment by poyalex** [comment]
Had meant to comment that out in my blog.js models file. Have already made the correction
